yelp_no_feature_3d3ae056:
    data_format: csv
    data_root: ../data/
    feature_cols:
    -   active: true
        dtype: str
        name: [user_id, business_id]
        type: categorical
    label_col: {dtype: float, name: target}
    min_categr_count: 1
    train_data: ../data/train.csv
    valid_data: ../data/valid.csv
