DeepFM_yelp_count_encoding_001_e00588ac:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_count_encoding_b2d46040
    debug: false
    embedding_dim: 64
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_count_encoding_002_f409ce08:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_count_encoding_b2d46040
    debug: false
    embedding_dim: 128
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_count_encoding_003_8e129777:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_count_encoding_b2d46040
    debug: false
    embedding_dim: 256
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_count_encoding_004_7764bf1e:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_count_encoding_b2d46040
    debug: false
    embedding_dim: 64
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_count_encoding_005_9462a6b6:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_count_encoding_b2d46040
    debug: false
    embedding_dim: 128
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_count_encoding_006_88b6e656:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_count_encoding_b2d46040
    debug: false
    embedding_dim: 256
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_count_encoding_007_a22209ce:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_count_encoding_b2d46040
    debug: false
    embedding_dim: 64
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_count_encoding_008_58c74eee:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_count_encoding_b2d46040
    debug: false
    embedding_dim: 128
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_count_encoding_009_58acfdaf:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_count_encoding_b2d46040
    debug: false
    embedding_dim: 256
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_count_encoding_010_47aff451:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_count_encoding_b2d46040
    debug: false
    embedding_dim: 64
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_count_encoding_011_6d1ddf03:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_count_encoding_b2d46040
    debug: false
    embedding_dim: 128
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_count_encoding_012_3e90a2fa:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_count_encoding_b2d46040
    debug: false
    embedding_dim: 256
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_count_encoding_013_77ca4f4f:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_count_encoding_b2d46040
    debug: false
    embedding_dim: 64
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_count_encoding_014_25d003bd:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_count_encoding_b2d46040
    debug: false
    embedding_dim: 128
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_count_encoding_015_bad91adf:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_count_encoding_b2d46040
    debug: false
    embedding_dim: 256
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_count_encoding_016_75687b53:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_count_encoding_b2d46040
    debug: false
    embedding_dim: 64
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_count_encoding_017_182318ab:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_count_encoding_b2d46040
    debug: false
    embedding_dim: 128
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_count_encoding_018_b16d0df3:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_count_encoding_b2d46040
    debug: false
    embedding_dim: 256
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_count_encoding_019_5747de84:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_count_encoding_b2d46040
    debug: false
    embedding_dim: 64
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_count_encoding_020_e7a51908:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_count_encoding_b2d46040
    debug: false
    embedding_dim: 128
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_count_encoding_021_3f6d0677:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_count_encoding_b2d46040
    debug: false
    embedding_dim: 256
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_count_encoding_022_6b0fc175:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_count_encoding_b2d46040
    debug: false
    embedding_dim: 64
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_count_encoding_023_f67af485:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_count_encoding_b2d46040
    debug: false
    embedding_dim: 128
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_count_encoding_024_2a861cab:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_count_encoding_b2d46040
    debug: false
    embedding_dim: 256
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
