DeepFM_yelp_business_feature_001_063be79c:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_business_feature_e143bbe8
    debug: false
    embedding_dim: 64
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_business_feature_002_19df6d83:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_business_feature_e143bbe8
    debug: false
    embedding_dim: 128
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_business_feature_003_7b6d2fb6:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_business_feature_e143bbe8
    debug: false
    embedding_dim: 256
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_business_feature_004_f8ae59fc:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_business_feature_e143bbe8
    debug: false
    embedding_dim: 64
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_business_feature_005_64c3c76b:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_business_feature_e143bbe8
    debug: false
    embedding_dim: 128
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_business_feature_006_89f62da7:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_business_feature_e143bbe8
    debug: false
    embedding_dim: 256
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_business_feature_007_16acce90:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_business_feature_e143bbe8
    debug: false
    embedding_dim: 64
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_business_feature_008_274ac7d9:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_business_feature_e143bbe8
    debug: false
    embedding_dim: 128
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_business_feature_009_96d1a50f:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_business_feature_e143bbe8
    debug: false
    embedding_dim: 256
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_business_feature_010_2f62b172:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_business_feature_e143bbe8
    debug: false
    embedding_dim: 64
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_business_feature_011_0bbce5e4:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_business_feature_e143bbe8
    debug: false
    embedding_dim: 128
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_business_feature_012_d85c2a81:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_business_feature_e143bbe8
    debug: false
    embedding_dim: 256
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_business_feature_013_f58c205d:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_business_feature_e143bbe8
    debug: false
    embedding_dim: 64
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_business_feature_014_161c0866:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_business_feature_e143bbe8
    debug: false
    embedding_dim: 128
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_business_feature_015_8ce99586:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_business_feature_e143bbe8
    debug: false
    embedding_dim: 256
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_business_feature_016_030e27cd:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_business_feature_e143bbe8
    debug: false
    embedding_dim: 64
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_business_feature_017_555f948b:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_business_feature_e143bbe8
    debug: false
    embedding_dim: 128
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_business_feature_018_97c6229c:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_business_feature_e143bbe8
    debug: false
    embedding_dim: 256
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_business_feature_019_0d110923:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_business_feature_e143bbe8
    debug: false
    embedding_dim: 64
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_business_feature_020_0e982c7a:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_business_feature_e143bbe8
    debug: false
    embedding_dim: 128
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_business_feature_021_1d9c3489:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_business_feature_e143bbe8
    debug: false
    embedding_dim: 256
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_business_feature_022_333d095c:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_business_feature_e143bbe8
    debug: false
    embedding_dim: 64
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_business_feature_023_956d2fe1:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_business_feature_e143bbe8
    debug: false
    embedding_dim: 128
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_business_feature_024_2834bf2a:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_business_feature_e143bbe8
    debug: false
    embedding_dim: 256
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
