base_config: ../config/ # the location of base config
base_expid: DeepFM_base # the expid of default hyper-parameters
dataset_id: yelp_no_feature # the dataset_id used

tuner_space:
    model_root: '../models/' # the value will override the default value in FM_test
    embedding_dim: [16, 8] # the values in the list will be grid-searched
      # regularizer: [0, 1.e-6] #, 1.e-5] # the values in the list will be grid-searched
    learning_rate: 1.e-3 # it is equivalent to [1.e-3]
    batch_size: 128 # the value will override the default value in FM_test
    epochs: 1 
      # hidden_units: [64, 64]
