base_config: ../config/ # the location of base config
base_expid: DeepFM_base # the expid of default hyper-parameters
dataset_id: yelp_count_encoding # the dataset_id used

tuner_space:
    model_root: '../models/' # the value will override the default value in FM_test
    embedding_dim: [64, 128, 256] # the values in the list will be grid-searched
    # net_regularizer: [0, 1.e-6] #, 1.e-5] # the values in the list will be grid-searched
    embedding_regularizer: [0, 0.01]
    net_dropout: [0, 0.03]
    # batch_norm: [True, False]
    learning_rate: [1.e-3, 1.e-2]
    batch_size: 1024 
    epochs: 50
