DeepFM_yelp_categorify_001_dcf8c866:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_categorify_3d3c8155
    debug: false
    embedding_dim: 64
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_categorify_002_7e0cdd40:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_categorify_3d3c8155
    debug: false
    embedding_dim: 128
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_categorify_003_e5a67f05:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_categorify_3d3c8155
    debug: false
    embedding_dim: 256
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_categorify_004_37080d73:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_categorify_3d3c8155
    debug: false
    embedding_dim: 64
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_categorify_005_58fe6466:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_categorify_3d3c8155
    debug: false
    embedding_dim: 128
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_categorify_006_c6b97738:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_categorify_3d3c8155
    debug: false
    embedding_dim: 256
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_categorify_007_409238e2:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_categorify_3d3c8155
    debug: false
    embedding_dim: 64
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_categorify_008_0bc30782:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_categorify_3d3c8155
    debug: false
    embedding_dim: 128
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_categorify_009_7d6f5f63:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_categorify_3d3c8155
    debug: false
    embedding_dim: 256
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_categorify_010_468c71fe:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_categorify_3d3c8155
    debug: false
    embedding_dim: 64
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_categorify_011_9856772a:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_categorify_3d3c8155
    debug: false
    embedding_dim: 128
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_categorify_012_61f943e8:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_categorify_3d3c8155
    debug: false
    embedding_dim: 256
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_categorify_013_1e8e9d8c:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_categorify_3d3c8155
    debug: false
    embedding_dim: 64
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_categorify_014_c2ee7118:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_categorify_3d3c8155
    debug: false
    embedding_dim: 128
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_categorify_015_dd70b14d:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_categorify_3d3c8155
    debug: false
    embedding_dim: 256
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_categorify_016_83d69d19:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_categorify_3d3c8155
    debug: false
    embedding_dim: 64
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_categorify_017_f4b5ee67:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_categorify_3d3c8155
    debug: false
    embedding_dim: 128
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_categorify_018_6dda4411:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_categorify_3d3c8155
    debug: false
    embedding_dim: 256
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_categorify_019_87824bbc:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_categorify_3d3c8155
    debug: false
    embedding_dim: 64
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_categorify_020_e2251651:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_categorify_3d3c8155
    debug: false
    embedding_dim: 128
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_categorify_021_6694f923:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_categorify_3d3c8155
    debug: false
    embedding_dim: 256
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_categorify_022_a914b115:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_categorify_3d3c8155
    debug: false
    embedding_dim: 64
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_categorify_023_8fae6ffb:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_categorify_3d3c8155
    debug: false
    embedding_dim: 128
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_categorify_024_fca5377e:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_categorify_3d3c8155
    debug: false
    embedding_dim: 256
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
