DeepFM_yelp_no_feature_001_22ba5a0c:
    batch_norm: false
    batch_size: 128
    dataset_id: yelp_no_feature_3d3ae056
    debug: false
    embedding_dim: 16
    embedding_regularizer: 0
    epochs: 1
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [300, 300, 300]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_no_feature_002_4e0dd65c:
    batch_norm: false
    batch_size: 128
    dataset_id: yelp_no_feature_3d3ae056
    debug: false
    embedding_dim: 8
    embedding_regularizer: 0
    epochs: 1
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [300, 300, 300]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
