yelp_feature_engineer_392d950c:
    data_format: csv
    data_root: ../data/
    feature_cols:
    -   active: true
        dtype: str
        name: [user_id_Categorify, business_id_Categorify, bucketed_sentiment_scores_received_Categorify,
            postal_code_Categorify]
        type: categorical
    -   active: true
        dtype: float
        name: [average_stars, philly_reviews_Norm, philly_share_of_reviews, gender_score,
            business_stars, business_review_count_Norm, TE_postal_code, TE_business_id,
            TE_bucketed_sentiment_scores_received, CE_postal_code, CE_bucketed_sentiment_scores_received]
        type: numeric
    label_col: {dtype: float, name: target}
    min_categr_count: 1
    train_data: ../data/train.csv
    valid_data: ../data/valid.csv
