yelp_feature_4792baa3:
    data_format: csv
    data_root: ../data/
    feature_cols:
    -   active: true
        dtype: str
        name: [user_id, business_id, postal_code]
        type: categorical
    -   active: true
        dtype: float
        name: [user_review_count, average_stars, gender_score, philly_reviews, philly_share_of_reviews,
            business_stars, business_review_count]
        type: numeric
    label_col: {dtype: float, name: target}
    min_categr_count: 1
    train_data: ../data/train.csv
    valid_data: ../data/valid.csv
