DeepFM_yelp_feature_001_03e4b53d:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_feature_4792baa3
    debug: false
    embedding_dim: 64
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_feature_002_7f85efa5:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_feature_4792baa3
    debug: false
    embedding_dim: 128
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_feature_003_b71ca503:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_feature_4792baa3
    debug: false
    embedding_dim: 256
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_feature_004_da66f817:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_feature_4792baa3
    debug: false
    embedding_dim: 64
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_feature_005_2972f7f5:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_feature_4792baa3
    debug: false
    embedding_dim: 128
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_feature_006_9adf532d:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_feature_4792baa3
    debug: false
    embedding_dim: 256
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_feature_007_b53f1478:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_feature_4792baa3
    debug: false
    embedding_dim: 64
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_feature_008_762e09c2:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_feature_4792baa3
    debug: false
    embedding_dim: 128
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_feature_009_ed30b5fa:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_feature_4792baa3
    debug: false
    embedding_dim: 256
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_feature_010_6ae2c020:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_feature_4792baa3
    debug: false
    embedding_dim: 64
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_feature_011_92f14768:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_feature_4792baa3
    debug: false
    embedding_dim: 128
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_feature_012_817587a4:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_feature_4792baa3
    debug: false
    embedding_dim: 256
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_feature_013_13d3f7c2:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_feature_4792baa3
    debug: false
    embedding_dim: 64
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_feature_014_9f450893:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_feature_4792baa3
    debug: false
    embedding_dim: 128
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_feature_015_e310373d:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_feature_4792baa3
    debug: false
    embedding_dim: 256
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_feature_016_c64c11a6:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_feature_4792baa3
    debug: false
    embedding_dim: 64
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_feature_017_eeb63b8d:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_feature_4792baa3
    debug: false
    embedding_dim: 128
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_feature_018_8ec8411f:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_feature_4792baa3
    debug: false
    embedding_dim: 256
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_feature_019_41ac4806:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_feature_4792baa3
    debug: false
    embedding_dim: 64
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_feature_020_4e72011b:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_feature_4792baa3
    debug: false
    embedding_dim: 128
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_feature_021_8a22560d:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_feature_4792baa3
    debug: false
    embedding_dim: 256
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_feature_022_7c214c53:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_feature_4792baa3
    debug: false
    embedding_dim: 64
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_feature_023_f4f3e532:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_feature_4792baa3
    debug: false
    embedding_dim: 128
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_feature_024_1c257271:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_feature_4792baa3
    debug: false
    embedding_dim: 256
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
