DeepFM_yelp_all_feature_001_fcc15e44:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_all_feature_2cca3d6c
    debug: false
    embedding_dim: 64
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_all_feature_002_b2a0ebff:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_all_feature_2cca3d6c
    debug: false
    embedding_dim: 128
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_all_feature_003_d2448abf:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_all_feature_2cca3d6c
    debug: false
    embedding_dim: 256
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_all_feature_004_9096f793:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_all_feature_2cca3d6c
    debug: false
    embedding_dim: 64
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_all_feature_005_ad42237b:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_all_feature_2cca3d6c
    debug: false
    embedding_dim: 128
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_all_feature_006_c1fb60e3:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_all_feature_2cca3d6c
    debug: false
    embedding_dim: 256
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_all_feature_007_f86f8406:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_all_feature_2cca3d6c
    debug: false
    embedding_dim: 64
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_all_feature_008_73aaad3f:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_all_feature_2cca3d6c
    debug: false
    embedding_dim: 128
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_all_feature_009_267c606c:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_all_feature_2cca3d6c
    debug: false
    embedding_dim: 256
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_all_feature_010_339f22df:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_all_feature_2cca3d6c
    debug: false
    embedding_dim: 64
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_all_feature_011_e37a445d:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_all_feature_2cca3d6c
    debug: false
    embedding_dim: 128
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_all_feature_012_2c612322:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_all_feature_2cca3d6c
    debug: false
    embedding_dim: 256
    embedding_regularizer: 0
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_all_feature_013_40d82c8c:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_all_feature_2cca3d6c
    debug: false
    embedding_dim: 64
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_all_feature_014_13705cea:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_all_feature_2cca3d6c
    debug: false
    embedding_dim: 128
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_all_feature_015_c9ffd748:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_all_feature_2cca3d6c
    debug: false
    embedding_dim: 256
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_all_feature_016_0b67c687:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_all_feature_2cca3d6c
    debug: false
    embedding_dim: 64
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_all_feature_017_832dce70:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_all_feature_2cca3d6c
    debug: false
    embedding_dim: 128
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_all_feature_018_6acda412:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_all_feature_2cca3d6c
    debug: false
    embedding_dim: 256
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_all_feature_019_eabe7106:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_all_feature_2cca3d6c
    debug: false
    embedding_dim: 64
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_all_feature_020_1093784c:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_all_feature_2cca3d6c
    debug: false
    embedding_dim: 128
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_all_feature_021_072ea8b1:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_all_feature_2cca3d6c
    debug: false
    embedding_dim: 256
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_all_feature_022_c328dfaa:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_all_feature_2cca3d6c
    debug: false
    embedding_dim: 64
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_all_feature_023_e027d7e6:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_all_feature_2cca3d6c
    debug: false
    embedding_dim: 128
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
DeepFM_yelp_all_feature_024_8334f927:
    batch_norm: false
    batch_size: 1024
    dataset_id: yelp_all_feature_2cca3d6c
    debug: false
    embedding_dim: 256
    embedding_regularizer: 0.01
    epochs: 50
    every_x_epochs: 1
    hidden_activations: relu
    hidden_units: [400, 400, 400]
    learning_rate: 0.01
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DeepFM
    model_id: DeepFM_base
    model_root: ../models/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.03
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2019
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
