yelp_user_feature_2ccba91b:
    data_format: csv
    data_root: ../data/
    feature_cols:
    -   active: true
        dtype: str
        name: [user_id, business_id]
        type: categorical
    -   active: true
        dtype: float
        name: [average_stars, philly_reviews, philly_share_of_reviews, gender_score]
        type: numeric
    label_col: {dtype: float, name: target}
    min_categr_count: 1
    train_data: ../data/train.csv
    valid_data: ../data/valid.csv
