### Tiny data for tests only
yelp_no_feature:
    data_root: ../data/
    data_format: csv
    train_data: ../data/train.csv
    valid_data: ../data/valid.csv
    # test_data: ../data/tiny_data/test_sample.csv
    min_categr_count: 1
    feature_cols:
        [{name: [user_id, business_id],
                 active: True, dtype: str, type: categorical}]
    label_col: {name: target, dtype: float}

yelp_feature:
    data_root: ../data/
    data_format: csv
    train_data: ../data/train.csv
    valid_data: ../data/valid.csv
    # test_data: ../data/tiny_data/test_sample.csv
    min_categr_count: 1
    feature_cols:
        [{name: [user_id, business_id, postal_code],
                 active: True, dtype: str, type: categorical},
                   # {name: postal_code, active: True, dtype: float, type: categorical},
         {name: [user_review_count, average_stars, gender_score, philly_reviews, philly_share_of_reviews, business_stars, business_review_count],
                 active: True, dtype: float, type: numeric}]
    label_col: {name: target, dtype: float}

