### Tiny data for tests only
yelp_no_feature:
    data_root: ../data/
    data_format: csv
    train_data: ../data/train.csv
    valid_data: ../data/valid.csv
    # test_data: ../data/tiny_data/test_sample.csv
    min_categr_count: 1
    feature_cols:
        [{name: [user_id, business_id],
                 active: True, dtype: str, type: categorical}]
    label_col: {name: target, dtype: float}

yelp_user_feature:
    data_root: ../data/
    data_format: csv
    train_data: ../data/train.csv
    valid_data: ../data/valid.csv
    # test_data: ../data/tiny_data/test_sample.csv
    min_categr_count: 1
    feature_cols:
        [{name: [user_id, business_id],
                 active: True, dtype: str, type: categorical},
         {name: [average_stars, philly_reviews, philly_share_of_reviews, gender_score],
                 active: True, dtype: float, type: numeric}]
    label_col: {name: target, dtype: float}

yelp_business_feature:
    data_root: ../data/
    data_format: csv
    train_data: ../data/train.csv
    valid_data: ../data/valid.csv
    # test_data: ../data/tiny_data/test_sample.csv
    min_categr_count: 1
    feature_cols:
        [{name: [user_id, business_id, bucketed_sentiment_scores_received, postal_code],
                 active: True, dtype: str, type: categorical},
         {name: [business_stars, business_review_count],
                 active: True, dtype: float, type: numeric}]
    label_col: {name: target, dtype: float}

yelp_all_feature:
    data_root: ../data/
    data_format: csv
    train_data: ../data/train.csv
    valid_data: ../data/valid.csv
    # test_data: ../data/tiny_data/test_sample.csv
    min_categr_count: 1
    feature_cols:
        [{name: [user_id, business_id, bucketed_sentiment_scores_received, postal_code],
                 active: True, dtype: str, type: categorical},
                   # {name: postal_code, active: True, dtype: float, type: categorical},
         {name: [average_stars, philly_reviews, philly_share_of_reviews, gender_score, 
           business_stars, business_review_count],
                 active: True, dtype: float, type: numeric}]
    label_col: {name: target, dtype: float}

yelp_business_feature_no_reviewcount:
    data_root: ../data/
    data_format: csv
    train_data: ../data/train.csv
    valid_data: ../data/valid.csv
    # test_data: ../data/tiny_data/test_sample.csv
    min_categr_count: 1
    feature_cols:
        [{name: [user_id, business_id, bucketed_sentiment_scores_received, postal_code],
                 active: True, dtype: str, type: categorical},
         {name: [business_stars],
                 active: True, dtype: float, type: numeric}]
    label_col: {name: target, dtype: float}

yelp_all_feature_no_reviewcount:
    data_root: ../data/
    data_format: csv
    train_data: ../data/train.csv
    valid_data: ../data/valid.csv
    # test_data: ../data/tiny_data/test_sample.csv
    min_categr_count: 1
    feature_cols:
        [{name: [user_id, business_id, bucketed_sentiment_scores_received, postal_code],
                 active: True, dtype: str, type: categorical},
                   # {name: postal_code, active: True, dtype: float, type: categorical},
         {name: [average_stars, philly_reviews, philly_share_of_reviews, gender_score, 
           business_stars],
                 active: True, dtype: float, type: numeric}]
    label_col: {name: target, dtype: float}

yelp_feature_engineer:
    data_root: ../data/
    data_format: csv
    train_data: ../data/train.csv
    valid_data: ../data/valid.csv
    # test_data: ../data/tiny_data/test_sample.csv
    min_categr_count: 1
    feature_cols:
        [{name: [user_id_Categorify, business_id_Categorify, bucketed_sentiment_scores_received_Categorify, postal_code_Categorify],
                 active: True, dtype: str, type: categorical},
         {name: [average_stars, philly_reviews_Norm, philly_share_of_reviews, gender_score, 
           business_stars, business_review_count_Norm, TE_postal_code, TE_business_id, TE_bucketed_sentiment_scores_received, CE_postal_code, CE_bucketed_sentiment_scores_received],
                 active: True, dtype: float, type: numeric}]
    label_col: {name: target, dtype: float}

yelp_categorify:
    data_root: ../data/
    data_format: csv
    train_data: ../data/train.csv
    valid_data: ../data/valid.csv
    # test_data: ../data/tiny_data/test_sample.csv
    min_categr_count: 1
    feature_cols:
        [{name: [user_id_Categorify, business_id_Categorify, bucketed_sentiment_scores_received_Categorify, postal_code_Categorify],
                 active: True, dtype: str, type: categorical},
         {name: [average_stars, philly_reviews, philly_share_of_reviews, gender_score, 
           business_stars, business_review_count],
                 active: True, dtype: float, type: numeric}]
    label_col: {name: target, dtype: float}

yelp_target_encoding:
    data_root: ../data/
    data_format: csv
    train_data: ../data/train.csv
    valid_data: ../data/valid.csv
    # test_data: ../data/tiny_data/test_sample.csv
    min_categr_count: 1
    feature_cols:
        [{name: [user_id, business_id, bucketed_sentiment_scores_received, postal_code],
                 active: True, dtype: str, type: categorical},
         {name: [average_stars, philly_reviews, philly_share_of_reviews, gender_score, 
           business_stars, business_review_count, TE_postal_code, TE_business_id, TE_bucketed_sentiment_scores_received],
                 active: True, dtype: float, type: numeric}]
    label_col: {name: target, dtype: float}

yelp_count_encoding:
    data_root: ../data/
    data_format: csv
    train_data: ../data/train.csv
    valid_data: ../data/valid.csv
    # test_data: ../data/tiny_data/test_sample.csv
    min_categr_count: 1
    feature_cols:
        [{name: [user_id, business_id, bucketed_sentiment_scores_received, postal_code],
                 active: True, dtype: str, type: categorical},
         {name: [average_stars, philly_reviews, philly_share_of_reviews, gender_score, 
           business_stars, business_review_count, CE_postal_code, CE_bucketed_sentiment_scores_received],
                 active: True, dtype: float, type: numeric}]
    label_col: {name: target, dtype: float}
